version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(deps-mix)"
    groups:
      mix-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directories:
      - "*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(deps-docker)"
    groups:
      docker-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(deps-github-actions)"
    groups:
      github-actions-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
