---
kind: pipeline
name: default

services:
  - name: rabbit
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: ecs
    host:
      path: /etc/profile.d/ecs-credentials-endpoint

clone:
  depth: 1

steps:
  - name: cache-restore
    image: prima/drone-tools:1.15.0
    volumes:
      - name: ecs
        path: /etc/profile.d/ecs-credentials-endpoint
      - name: docker
        path: /var/run/docker.sock
    commands:
      - . /etc/profile.d/ecs-credentials-endpoint
      - cache-restore

  - name: build-image
    image: prima/drone-tools:1.15.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - sed -i 's/USER app/USER root/g' Dockerfile
      - docker build -t prima/amqpx-ci:1 .
    depends_on:
      - cache-restore

  - name: init
    image: prima/amqpx-ci:1
    commands:
      - mix deps.get
    depends_on:
      - build-image

  - name: compile-test
    image: prima/amqpx-ci:1
    environment:
      MIX_ENV: test
    commands:
      - mix compile --all-warnings --ignore-module-conflict --warnings-as-errors --debug-info
    depends_on:
      - init

  - name: format
    image: prima/amqpx-ci:1
    environment:
      MIX_ENV: test
    commands:
      - mix format --check-formatted mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs}" "priv/**/*.{ex,exs}" "config/**/*.{ex,exs}"
    depends_on:
      - compile-test

  - name: credo
    image: prima/amqpx-ci:1
    environment:
      MIX_ENV: test
    commands:
      - mix credo
    depends_on:
      - compile-test

  - name: dyalizer
    image: prima/amqpx-ci:1
    environment:
      MIX_ENV: test
    commands:
      - mix dialyzer --halt-exit-status
    depends_on:
      - compile-test

  - name: test
    image: prima/amqpx-ci:1
    environment:
      MIX_ENV: test
    commands:
      - mix test
    depends_on:
      - compile-test

  - name: publish
    image: prima/amqpx-ci:1
    environment:
      MIX_ENV: dev
      HEX_AUTH_KEY:
        from_secret: hex_auth_key
    commands:
      - mix compile
      - ./publish
    depends_on:
      - test
    when:
      event:
        - tag

  - name: cache-save
    image: prima/drone-tools:1.15.0
    volumes:
      - name: ecs
        path: /etc/profile.d/ecs-credentials-endpoint
      - name: docker
        path: /var/run/docker.sock
    commands:
      - . /etc/profile.d/ecs-credentials-endpoint
      - cache-save _build deps
    depends_on:
      - format
      - credo
      - dyalizer
      - test
    when:
      branch:
        - master

---
kind: pipeline
name: notify

clone:
  disable: true

steps:
  - name: notify_email
    image: drillster/drone-email
    environment:
      PLUGIN_USERNAME:
        from_secret: email_username
      PLUGIN_PASSWORD:
        from_secret: email_password
    settings:
      host: email-smtp.eu-west-1.amazonaws.com
      from: noreply@prima.it

trigger:
  status:
    - failure

depends_on:
  - default
