clone:
  cache-restore:
    image: prima/drone-tools:1.14.3
    volumes:
      - /var/cache/ci/${DRONE_REPO}/${DRONE_BRANCH}:/var/cache/ci
      - /etc/profile.d/ecs-credentials-endpoint:/etc/profile.d/ecs-credentials-endpoint
    commands:
      - . /etc/profile.d/ecs-credentials-endpoint
      - cache-restore --files --no-docker-cache-pull
  git:
    image: plugins/git
    recursive: false

pipeline:
  build:
    image: prima/drone-tools:1.14.3
    environment:
      - COMPOSE_PROJECT_NAME=${DRONE_REPO_NAME}${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/cache/ci/${DRONE_REPO}/${DRONE_BRANCH}:/var/cache/ci
      - /etc/profile.d/ecs-credentials-endpoint:/etc/profile.d/ecs-credentials-endpoint
    commands:
      - . /etc/profile.d/ecs-credentials-endpoint
      - prepare-docker-compose
      - cache-restore --docker-cache-pull --no-files
      - docker-compose build
      - docker-compose run web mix deps.get
      - docker-compose run -e MIX_ENV=test web mix compile --all-warnings --warnings-as-errors --ignore-module-conflict --debug-info
      - docker-compose run -e MIX_ENV=test web mix check
      # - docker-compose run -e MIX_ENV=test web mix test
      - cache-save deps _build ~/.cache

  notify_email:
    image: drillster/drone-email
    host: email-smtp.eu-west-1.amazonaws.com
    secrets: [ email_username, email_password ]
    from: noreply@prima.it
    when:
      status: [ changed, failure ]

  cleanup:
    image: prima/drone-tools:1.14.3
    environment:
      - COMPOSE_PROJECT_NAME=${DRONE_REPO_NAME}${DRONE_BUILD_NUMBER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - teardown
    when:
      status: [ success, killed, failure ]
