version: "2"
services:
  console:
    build: .
    volumes:
      - .:/code:delegated
    working_dir: /code
    stdin_open: true 
    tty: true
    command: bash
    depends_on:
      rabbit:
        condition: service_started
      rabbit_two:
        condition: service_healthy

  rabbit:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: amqpx
      RABBITMQ_DEFAULT_PASS: amqpx
    ports:
      - "23555:15672"
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 10s
      timeout: 5s
      retries: 3

  rabbit_two:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_VHOST: /two
      RABBITMQ_DEFAULT_USER: amqpx
      RABBITMQ_DEFAULT_PASS: amqpx
    ports:
      - "23556:15672"
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 10s
      timeout: 5s
      retries: 3
