#!/usr/bin/env bash
# source /setup_common.sh
# source /decrypt_secrets.sh

if [ "$1" == "mix" ]; then
  exec "$@"
elif [ -n "$1" ]; then
  sh -c "$@"
else
  mix deps.get
  mix ecto.setup
  mix phx.server

  trap : TERM INT; sleep infinity & wait
fi
